-- Create the table
CREATE TABLE scores (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  score bigint not null
);

-- Enable Row Level Security (RLS)
ALTER TABLE scores ENABLE ROW LEVEL SECURITY;

-- Create Policy: Allow anyone (anon) to VIEW scores
CREATE POLICY "Enable read access for all users" 
ON scores FOR SELECT 
USING (true);

-- Create Policy: Allow anyone (anon) to ADD scores
CREATE POLICY "Enable insert access for all users" 
ON scores FOR INSERT 
WITH CHECK (true);
